### ISSUE TITLE
[São José dos Campos] Front End AngularJS 2+ na Atech grupo Embraer

### ISSUE THREAD

**Issue by salgadorw** [frontinvale/vagas#6]
## Descrição da vaga

#vaga #developer #frontend #sjc #emprego #oportunidade
DESENVOLVEDOR FRONT END 
Necessário: HTML5, XHTML, Java Script, jQuery, AJAX, CSS3, SASS, One Page, Responsividade e Bootstrap 
AngularJS 2+ e Material Design (frameworks).

Local de trabalho: São José dos Campos
Enviar currículo para rsalgado@atech.com.br com assunto "FRONT END"
## Local

São José dos Campos - Atech

## Benefícios

- Plano de saúde
- Seguro de vida
- Auxílio creche
- ...

#### Diferenciais

- ...

## Contratação

CLT

## Como se candidatar

rsalgado@atech.com.br

**Comment by silviorodrigues** [comment]
@salgadonline qual o nível da vaga? Junior, Pleno ou Sênior?
Somente alocado ou aceita remoto?
